name: Check Merge
on: pull_request

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  check-merge:
    runs-on: ubuntu-latest
    if: github.base_ref == 'master'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find Release PR
      run: |
        PR_URL=$(gh pr list --base production --label release --state open --json url --jq '.[0].url')
        echo "PR_URL=$PR_URL" >> $GITHUB_ENV

    - name: Convert open PRs to Draft
      if: env.PR_URL
      run: >
        gh pr list --base master --state open |
        awk '{print $1}' |
        xargs -I{} sh -c 'gh pr ready --undo {}; gh pr comment --body ":x: Blocked by ${{ env.PR_URL }}" {}'
