name: Create Pull Request
on:
  push:
    branches:
      - master
      - production

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  pre-release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # master -> production
    - name: Create Release PR
      run: |
        DATE=$(date +'%Y-%m-%d')
        PR_URL=$(gh pr create --base production --fill --label release --title $DATE)
        echo "PR_URL=$PR_URL" >> $GITHUB_ENV
      continue-on-error: true

    - name: Convert open PRs to Draft
      if: env.PR_URL
      run: >
        gh pr list --base master --draft=false --state open |
        awk '{print $1}' |
        xargs -I{} sh -c 'gh pr ready --undo {}; gh pr comment --body ":x: Blocked by ${{ env.PR_URL }}" {}'

  post-release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'production'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert draft PRs to Ready
      run: >
        gh pr list --base master --draft --state open |
        awk '{print $1}' |
        xargs -I{} sh -c 'gh pr ready {}; gh pr comment --body ":white_check_mark: Ready for review" {}'
