name: Pull Request
on:
  push:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # master -> production
    - name: Create Pull Request
      run: |
        DATE=$(date +'%Y-%m-%d')
        gh pr create --base production --fill --label release --title $DATE
      env:
        GITHUB_TOKEN: ${{ github.token }}
      continue-on-error: true
