name: Release
on:
  push:
    branches:
      - master
      - production

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  pre-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # master -> production
    - name: Create Release PR
      run: |
        DATE=$(date +'%Y-%m-%d')
        gh pr create --base production --fill --label release --title $DATE
      continue-on-error: true

    - name: Convert open PRs to Draft
      if: env.RELEASE_PR
      run: >
        gh pr list --base master --draft false --state open |
        awk '{print $1}' |
        xargs -I{} sh -c 'gh pr ready --undo {}; gh pr comment --body ":x: Waiting on #${{ env.RELEASE_PR }}" {}'

  post-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Convert open PRs to Ready
      run: >
        gh pr list --base master --state open |
        awk '{print $1}' |
        xargs -I{} sh -c 'gh pr ready {}; gh pr comment --body ":white_check_mark: Ready to merge" {}'
